'use strict';

const MOTION_TABLE = 'NEO_APP_ROBOT_MOTION';
const LEGACY_TABLES = ['NEO_APP_LEROBOT_MOTION', 'NEO_APP_ROBOT_RUN'];
const DDLS = [
  `CREATE TAG TABLE IF NOT EXISTS ${MOTION_TABLE} (
    NAME VARCHAR(128) PRIMARY KEY,
    TIME DATETIME BASETIME,
    VALUE DOUBLE,
    J2 DOUBLE,
    J3 DOUBLE,
    J4 DOUBLE,
    J5 DOUBLE,
    J6 DOUBLE,
    J7 DOUBLE,
    SAMPLE_NO INTEGER,
    PLAYBACK_MS LONG,
    SOURCE_SECONDS DOUBLE,
    SOURCE_TIMESTAMP LONG
  )
  METADATA (
    TAG_KIND VARCHAR(16),
    RUN_ID VARCHAR(64),
    LOGICAL_NAME VARCHAR(96),
    MODEL_ID VARCHAR(40),
    SOURCE_KIND VARCHAR(24),
    SCENARIO_ID VARCHAR(48),
    USER_NO INTEGER,
    TASK_NO INTEGER,
    DOF INTEGER,
    FRAME_COUNT INTEGER,
    SCENARIO_COUNT INTEGER,
    DURATION_MS LONG,
    START_TIME DATETIME,
    END_TIME DATETIME
  )`
];

function ensureSchema(connection) {
  // Setup is explicit and preserves the previous sample table and all existing data.
  return DDLS.map((ddl) => connection.exec(ddl));
}

module.exports = { MOTION_TABLE, LEGACY_TABLES, DDLS, ensureSchema };
