'use strict';

const MOTION_TABLE = 'NEO_APP_ROBOT_MOTION';
const RUN_TABLE = 'NEO_APP_ROBOT_RUN';
const DDLS = [
  `CREATE TAG TABLE IF NOT EXISTS ${MOTION_TABLE} (
    NAME VARCHAR(96) PRIMARY KEY,
    TIME DATETIME BASETIME,
    VALUE DOUBLE,
    J2 DOUBLE,
    J3 DOUBLE,
    J4 DOUBLE,
    J5 DOUBLE,
    J6 DOUBLE,
    J7 DOUBLE,
    RUN_ID VARCHAR(64),
    MODEL_ID VARCHAR(40),
    SCENARIO_ID VARCHAR(48),
    USER_NO INTEGER,
    TASK_NO INTEGER,
    SAMPLE_NO INTEGER,
    PLAYBACK_MS LONG,
    SOURCE_SECONDS DOUBLE,
    SOURCE_TIMESTAMP LONG,
    SOURCE_KIND VARCHAR(24)
  )`,
  `CREATE TAG TABLE IF NOT EXISTS ${RUN_TABLE} (
    NAME VARCHAR(96) PRIMARY KEY,
    TIME DATETIME BASETIME,
    VALUE DOUBLE,
    RUN_ID VARCHAR(64),
    MODEL_ID VARCHAR(40),
    SOURCE_KIND VARCHAR(24),
    FRAME_COUNT INTEGER,
    SCENARIO_COUNT INTEGER,
    DURATION_MS LONG
  )`
];

function ensureSchema(connection) {
  // Setup is explicit and preserves the previous sample table and all existing data.
  return DDLS.map((ddl) => connection.exec(ddl));
}

module.exports = { MOTION_TABLE, RUN_TABLE, DDLS, ensureSchema };
